"""Shared Pydantic models, enums and wire constants for the medialab service suite."""

from medialab_contracts.constants import (
    API_KEY_HEADER,
    API_PREFIX,
    HEALTH_PATH,
    MEDIA_TYPE_SUBDIRS,
    STAGING_SUBDIR,
)
from medialab_contracts.discover import (
    TMDB_IMAGE_BASE_URL,
    DiscoverItem,
    DiscoverResponse,
    Genre,
    GenresResponse,
    LibraryTmdbIdsResponse,
    PosterSize,
    poster_url,
)
from medialab_contracts.errors import CommonErrorCode, ErrorResponse
from medialab_contracts.media import MediaType
from medialab_contracts.progress import ETA_UNKNOWN_SECONDS, JobProgress
from medialab_contracts.search import TorrentSearchScope
from medialab_contracts.settings import (
    SettingSource,
    SettingSpec,
    SettingsResponse,
    SettingType,
    SettingUpdate,
    SettingValue,
    SettingView,
    SuiteSettingsResponse,
)
from medialab_contracts.shows import (
    STILL_SIZE,
    Episode,
    EpisodeKey,
    EpisodeState,
    LibraryEpisodesResponse,
    Season,
    SeriesEpisodesResponse,
    ShowBrowseResponse,
    still_url,
)
from medialab_contracts.transfers import TransferHashInfo, TransferInfo
from medialab_contracts.videos import (
    YOUTUBE_EMBED_BASE_URL,
    Video,
    VideosResponse,
    VideoType,
    youtube_embed_url,
)
from medialab_contracts.watchlist import (
    DEFAULT_FOLLOW_RESOLUTION,
    FollowRequest,
    FollowStart,
    FollowStartMode,
    FollowState,
    SeasonDecisionRequest,
    SeasonFollowMode,
    SeasonFollowState,
    SubmissionState,
    WatchlistAddRequest,
    WatchlistItem,
    WatchlistKind,
    WatchlistResponse,
)

__all__ = [
    "API_KEY_HEADER",
    "API_PREFIX",
    "CommonErrorCode",
    "DEFAULT_FOLLOW_RESOLUTION",
    "DiscoverItem",
    "DiscoverResponse",
    "ETA_UNKNOWN_SECONDS",
    "Episode",
    "EpisodeKey",
    "EpisodeState",
    "ErrorResponse",
    "FollowRequest",
    "FollowStart",
    "FollowStartMode",
    "FollowState",
    "Genre",
    "GenresResponse",
    "HEALTH_PATH",
    "JobProgress",
    "LibraryEpisodesResponse",
    "LibraryTmdbIdsResponse",
    "MEDIA_TYPE_SUBDIRS",
    "MediaType",
    "PosterSize",
    "STAGING_SUBDIR",
    "STILL_SIZE",
    "Season",
    "SeriesEpisodesResponse",
    "SettingSource",
    "SettingSpec",
    "SettingType",
    "SettingUpdate",
    "SettingValue",
    "SeasonDecisionRequest",
    "SeasonFollowMode",
    "SeasonFollowState",
    "SettingView",
    "SettingsResponse",
    "ShowBrowseResponse",
    "SubmissionState",
    "SuiteSettingsResponse",
    "TMDB_IMAGE_BASE_URL",
    "TorrentSearchScope",
    "TransferHashInfo",
    "TransferInfo",
    "Video",
    "VideoType",
    "VideosResponse",
    "WatchlistAddRequest",
    "WatchlistItem",
    "WatchlistKind",
    "WatchlistResponse",
    "YOUTUBE_EMBED_BASE_URL",
    "poster_url",
    "still_url",
    "youtube_embed_url",
]
